version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_graphql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_graphql
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    volumes:
      - .:/app
    command: >
      sh -c "
        until nc -z -v -w30 $DB_HOST $DB_PORT; do
          echo 'Waiting for database connection...';
          sleep 5;
        done;
        npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run start:dev
      "

volumes:
  postgres_data:
