version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_graphql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: graphql_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_graphql
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=graphql_db
      - DB_PORT=5432
    volumes:
      - .:/app
    command: >
      sh -c "
        until nc -z -v -w30 db 5432; do
          echo 'Waiting for database connection...';
          sleep 5;
        done;
        npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm run start:dev
      "
      
volumes:
  postgres_data:
